import type { Config } from 'tailwindcss';

// Tokens lifted verbatim from _archive/design/home_modernized/code.html (lines 12-99).
// Do not "improve" — designs depend on these exact values.
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'background': '#0a192f',
        'on-background': '#e0e3e6',
        'surface': '#0a192f',
        'surface-dim': '#0a192f',
        'surface-bright': '#1e3252',
        'surface-container-lowest': '#060f1e',
        'surface-container-low': '#0f1d33',
        'surface-container': '#13243d',
        'surface-container-high': '#1a2d48',
        'surface-container-highest': '#233754',
        'surface-variant': '#233754',
        'on-surface': '#e0e3e6',
        'on-surface-variant': '#c5c6cd',
        'surface-tint': '#b9c7e4',
        'inverse-surface': '#e0e3e6',
        'inverse-on-surface': '#1a2d48',
        'outline': '#8f9097',
        'outline-variant': '#3b4a61',
        'primary': '#b9c7e4',
        'on-primary': '#233148',
        'primary-container': '#0a192f',
        'on-primary-container': '#74829d',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b9c7e4',
        'on-primary-fixed': '#0d1c32',
        'on-primary-fixed-variant': '#39475f',
        'inverse-primary': '#515f78',
        'secondary': '#7df4ff',
        'on-secondary': '#002022',
        'secondary-container': '#00dbe9',
        'on-secondary-container': '#00363a',
        'secondary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#00dbe9',
        'on-secondary-fixed': '#002022',
        'on-secondary-fixed-variant': '#004f54',
        'tertiary': '#b9c7e4',
        'on-tertiary': '#233148',
        'tertiary-container': '#1a2d48',
        'on-tertiary-container': '#b9c7e4',
        'tertiary-fixed': '#d6e3ff',
        'tertiary-fixed-dim': '#b9c7e4',
        'on-tertiary-fixed': '#0d1c32',
        'on-tertiary-fixed-variant': '#39475f',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        'container-max': '1440px',
        'section-gap': '128px',
      },
      fontFamily: {
        'body-md': ['var(--font-inter)'],
        'body-lg': ['var(--font-inter)'],
        'headline-md': ['var(--font-hanken)'],
        'headline-lg': ['var(--font-hanken)'],
        'headline-lg-mobile': ['var(--font-hanken)'],
        'display-xl': ['var(--font-hanken)'],
        'label-technical': ['var(--font-jetbrains)'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg': ['var(--text-headline-lg, 48px)', { lineHeight: 'var(--leading-headline-lg, 56px)', fontWeight: '700' }],
        'headline-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'display-xl': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-technical': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      backdropBlur: {
        glass: '20px',
      },
      boxShadow: {
        glow: '0px 0px 15px rgba(0, 219, 233, 0.4)',
        'glow-blue': '0px 0px 15px rgba(0, 219, 233, 0.4)',
      },
    },
  },
  plugins: [],
};

export default config;
